POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Mikon toinen blogi",
  "author": "Mikko",
  "url": "http://esimerkki.fi",
  "likes": 100,
  "userId": "667a873f9f31656f42de3966"
}